server:
  port: 8193
  servlet:
    context-path: /market-cart

integrations:
  product-service:
    url: http://localhost:8192/market-core/
    connect-timeout: 50000
    read-timeout: 10000
    write-timeout: 5000